spring.application.name=greenhand

# ? MariaDB ??
spring.datasource.url=jdbc:mariadb://192.168.0.30:3306/greenhand?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=user1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ? JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

# ? URI ??? (?? ??)
server.tomcat.uri-encoding=UTF-8

# ? SQL ??
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
